# Generated by Django 4.2.7 on 2023-12-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="default_vocoder_id",
            field=models.CharField(
                blank=True, default="GBv7mTt0atIp3Br8iCZE", max_length=100, null=True
            ),
        ),
    ]
