# Generated by Django 4.2.7 on 2023-12-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0002_alter_customer_default_vocoder_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="default_vocoder_id",
            field=models.CharField(default="GBv7mTt0atIp3Br8iCZE", max_length=100),
        ),
    ]
